# Generated by Django 5.1.4 on 2024-12-30 13:40

import dev_pro.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPatientreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_details_id', models.CharField(max_length=100)),
                ('report_file', models.FileField(blank=True, upload_to=dev_pro.models.NewPatientreports.nameFile)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewPatientsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('procedure', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('patient_email', models.EmailField(max_length=254, unique=True)),
                ('referred', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patientsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('procedure', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('patient_email', models.EmailField(max_length=254, unique=True)),
                ('referred', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patientreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, upload_to=dev_pro.models.Patientreports.nameFile)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_pro.patientsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('speciality', models.CharField(max_length=50)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
